name: tests

on: [ 'push', 'pull_request' ]

jobs:
  ci:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
      - name: Install Dependencies
        run: composer update --no-interaction --no-progress
      - name: Run Tests
        run: composer test