name: tests
on: [
  'push',
  'pull_request'
]
jobs:
  ci:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
      - name: Install Dependencies
        run: composer update --no-interaction --no-progress
      - name: Run Tests
        run: composer pest